apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysecondpod
  name: mysecondpod
spec:
  containers:
  - image: coolgourav147/nginx-custom
    name: mysecondpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
