apiVersion: v1
kind: ReplicationController 
metadata: 
  name: firstreplicacontroller
  labels:
    proj: voting
spec: 
  replicas: 2
  # selector:
    #  env: prod  -- shouold match with container labels
  template:
    metadata:     
      name: myfirstpod
      labels: 
        env: prod
    spec: 
      containers:
        - name: containername
          image: coolgourav147/nginx-custom:v2
          env:
            - name: myname
              value: ArunSingh
          args: ["sleep", "5000"]
