apiVersion: v1
kind: Service
metadata:
  name: servicetest1
  labels:
    env: dev
    servicelabel: service
spec:
  type: NodePort
  ports:
    - nodePort: 32000
      port: 8000
      targetPort: 80
  selector:
    type: app
