apiVersion: v1
kind: ReplicationController 
metadata: 
  name: firstreplicacontroller
  labels:
    env: prod
spec: 
  replicas: 2
  template:
    metadata:     
      name: myfirstpod
      labels: 
        env: prod
        job: start 
    spec: 
      containers:
        - name: containername
          image: coolgourav147/nginx-custom:v2
          env:
            - name: myname
              value: ArunSingh
            - name: city
              value: Basti
          args: ["sleep", "5000"]
