apiVersion: v1
kind: Pod
metadata:
  name: mysecondpod
  labels: 
    env: prod
    job: start 
spec: 
  containers:
    - name: firstcontainer
      image: coolgourav147/nginx-custom
      env:
        - name: myname
          value: ArunSingh
        - name: city
          value: Basti
      args: ["sleep", "3600"]
    - name: secondcontainer
      image: coolgourav147/nginx-custom
